version: '3'
services:
  flask-api:
    build: .
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: run.py
      FLASK_ENV: development
      MONGO_URI: "mongodb://mongo:27017/flask_api"
    depends_on:
      - mongo
  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
